### ISSUE TITLE
Multiple rtpengine servers

### ISSUE THREAD

**Issue by sashasaturn** [davehorton/drachtio-siprec-recording-server#12]
Hello Dave,

Is it supported to have multiple rtpengine instances?

From the code I assume that currently it's not supported, but maybe you have this feature on your roadmap?

Thanks,

Alxe

**Comment by davehorton** [comment]
Yes, you could definitely do this, pretty easily.  Changes to the code would be relatively minor.  If I have time in the next few days I will try to do a pull request for this (but no guarantees)

**Comment by sashasaturn** [comment]
Thank you very much Dave!

**Comment by davehorton** [comment]
ok, now you can provide an array of rtpengine servers if you want (it's still valid to provide a single rtpengine config object) and it will round robin calls across them
