### ISSUE TITLE
Failure in negotiation with RTP Engine

### ISSUE THREAD

**Issue by arikhalperin** [davehorton/drachtio-siprec-recording-server#17]
My recording server fails to negotiate with RTP engine:

NGREP from RTP engine:
==================

interface: eth0 (157.245.128.0/255.255.240.0)
filter: ( port 2223 ) and ((ip || ip6) || (vlan && (ip || ip6)))

U 167.99.248.68:57002 -> 157.245.136.128:2223
9c6c291f-bd1c-49fd-941d-2cf485de8a4a d3:ICE6:remove7:call-id25:B2B.64.8009998.15693997447:command5:offer8:from-tag37:61a826a6ff880a19c31acdfc1fc2d111-ce2111:record call3:yes7:replacel6:origin18:session-connectione3:sdp174:v=0.
o=- 1569399744 0 IN IP4 0.0.0.0.
s=-.
c=IN IP4 127.0.0.1.
t=0 0.
m=audio 35012 RTP/AVP 0 101.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=label:1.
a=sendonly.
e

U 157.245.136.128:2223 -> 167.99.248.68:57002
9c6c291f-bd1c-49fd-941d-2cf485de8a4a d10:recordingsle6:result5:error12:error-reason19:Error rewriting SDPe

On the drechtio server I get a timeout for SIP REC
===================================

T 172.17.0.2:9022 -> 172.17.0.1:40722 [AP]
517#a68f8408-8e2c-4b40-8239-ae6ca7001fa4|sip|network|375|udp|167.99.248.68|5060|08:29:32.403739|05e9f1ed-f75b-4895-a3e5-fd84b795e704|.
CANCEL sip:172.17.0.2:5060 SIP/2.0.
Via: SIP/2.0/UDP 167.99.248.68:5060;branch=z9hG4bK94f6.825bc433.0;rport=5060.
From: <sip:172.17.0.2:5060>;tag=61a826a6ff880a19c31acdfc1fc2d111-ce21.
Call-ID: B2B.64.6780361.1569400142.
To: sip:172.17.0.2:5060.
CSeq: 2 CANCEL.
Max-Forwards: 70.
Reason: SIP;cause=480;text="NO_ANSWER".
User-Agent: OpenSIPS (3.0.0 (x86_64/linux)).
Content-Length: 0.
.

Output from the recording server:
========================

{"level":30,"time":1569399924140,"msg":"attempting inbound connection","pid":20377,"hostname":"opensips","host":"172.17.0.2","port":9022,"secret":"cymru","v":1}
{"level":30,"time":1569399924149,"msg":"using rtpengine as the recorder","pid":20377,"hostname":"opensips","remote":{"host":"157.245.136.128","port":2223},"v":1}
{"level":30,"time":1569399924234,"msg":"inbound connection to drachtio listening on tcp/172.17.0.2:5060,udp/172.17.0.2:5060","pid":20377,"hostname":"opensips","v":1}
{"level":30,"time":1569400142303,"msg":"received SIPREC invite: sip:172.17.0.2:5060","pid":20377,"hostname":"opensips","callid":"B2B.64.6780361.1569400142","v":1}
{"level":50,"time":1569400142489,"msg":"Error connecting call: Error: error connecting to rtpengine","pid":20377,"hostname":"opensips","callid":"B2B.64.6780361.1569400142","v":1}

Attaching: pcap, recording server config, opensips config

[log.pcap.log](https://github.com/davehorton/drachtio-siprec-recording-server/files/3653740/log.pcap.log)

[opensips.cfg.log](https://github.com/davehorton/drachtio-siprec-recording-server/files/3653741/opensips.cfg.log)

[local.json.log](https://github.com/davehorton/drachtio-siprec-recording-server/files/3653742/local.json.log)

**Comment by davehorton** [comment]
can you also get the rtpengine log ?  It usually shows up in /var/log/syslog

**Comment by davehorton** [comment]
also please incliude the drachtio server log

**Comment by arikhalperin** [comment]
Closing this issue. I found an error on the RTP Engine side. Thank you!

**Comment by arikhalperin** [comment]
Thanks! Got it to work.

However I just realised - I want to use real time transcription, so a cap format will not do.

I’ll repeat the process with a free switch.

Arik
