### ISSUE TITLE
Error: Response#send: status is required and must be a valid sip response code

### ISSUE THREAD

**Issue by ajay-sabat** [davehorton/drachtio-siprec-recording-server#19]
Hi,

It had been working fine for a while without any issues. Suddenly all calls to Drachtio are failing. The error is from the Drachtio siprec server as given below. The log snippet below contains the log messages from startup up to a call.

> {"level":30,"time":1571957280234,"msg":"attempting inbound connection","pid":8,"hostname":"siprec-proxy-application-584cf8699b-hhs68","host":"10.252.1.9","port":9022,"secret":"cymru","v":1}
{"level":30,"time":1571957280327,"msg":"using freeswitch as the recorder","pid":8,"hostname":"siprec-proxy-application-584cf8699b-hhs68","0":"","v":1}
{"level":30,"time":1571957280927,"msg":"successfully connected to redis at redis:6379","pid":8,"hostname":"siprec-proxy-application-584cf8699b-hhs68","v":1}
{"level":30,"time":1571957280934,"msg":"inbound connection to drachtio listening on tcp/34.82.88.194:5060,udp/34.82.88.194:5060","pid":8,"hostname":"siprec-proxy-application-584cf8699b-hhs68","v":1}

> {"level":30,"time":1571961613618,"msg":"received SIPREC invite: sip:SIPREC-SRS@34.82.88.194:5060","pid":8,"hostname":"siprec-proxy-application-584cf8699b-hhs68","callid":"6292233_16782162_93564885@209.119.33.6","v":1}
(node:8) UnhandledPromiseRejectionWarning: Error: Response#send: status is required and must be a valid sip response code
    at Response.send (/usr/src/app/node_modules/drachtio-srf/lib/response.js:80:13)
    at createUAC.then.catch (/usr/src/app/node_modules/drachtio-srf/lib/srf.js:797:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I appreciate any help to troubleshoot or fix the issue.

Thanks!

**Comment by davehorton** [comment]
Can you run a call through with DEBUG=drachtio:*, ie
```
DEBUG=drachtio:* node app.js
```
and provide the output?

**Comment by ajay-sabat** [comment]
Hi Dave,

Thanks for quick reply.
Please find attached the logs with loglevel DEBUG as suggested by you.

-- Ajay

[drachtio_siprec_controller_error_102819_test1.log](https://github.com/davehorton/drachtio-siprec-recording-server/files/3780126/drachtio_siprec_controller_error_102819_test1.log)

**Comment by davehorton** [comment]
You are using freeswitch as the media server, and it appears like there are no freeswitch entries in your config file.

**Comment by ajay-sabat** [comment]
Dave,
Thanks for your help and quick reply.
Yes, some change in network infrastructure caused an environment variable which fills in this configuration remained empty.
Since it was working fine for a long time and the error seemed like a bigger issue, I couldn't think this as a configuration issue.
-- Ajay
