### ISSUE TITLE
Voice is over lapping 

### ISSUE THREAD

**Issue by petertestalpha** [davehorton/drachtio-siprec-recording-server#28]
I Follow your instruction of  this repository but 
when I listen recorded files of each call then it's have an issue that call 
When I say Hi after that get  I response :-> Welcome, I am bot How can I help you Everything is fine with call
 but when I play  recorded file I listen bot voice first then I listen my voice some time it''s over lap sometime my voice come after bot response 

We want to know How to fix that

**Comment by davehorton** [comment]
are you recording using freeswitch or rtpengine

**Comment by petertestalpha** [comment]
Freeswitch 
When I turn on stereo mode in dialplan I am able to listen my voice in right speaker and bot respond in left speaker also my voice become loader when i turn on stereo mode but overlapping problem not solved I made little change in your javascript to direct stream text to speech instead of making audio file

**Comment by davehorton** [comment]
Sounds like an issue with the incoming stream (comfort noise) or your freeswitch config, not this application.

**Comment by petertestalpha** [comment]
Yes problem with incoming user voice overlap  with bot response voice
In freeswitch config we made change as per your instruction of this  repository
